AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  COOL GUYS ONLY. DON'T ASK!

Globals:
  Function:
    Timeout: 3

Resources:
  CrawlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: [ "index.crawler" ]
    Metadata:
      DockerTag: nodejs14.x-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  CrawlerFnArn:
    Description: "Crawler Function Arn"
    Value: !GetAtt CrawlerFunction.Arn
